# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c9c7258f1194ca904a76ccccdabe1a69be5163f4583f29dabf93158a143e9d7b3b1f8a283ce6712a51f00086d245582fa2d60e88f57ba8ab341de9cca22d47

test:
  secret_key_base: 155988374b42b2c35e1a93f2056f1c599d564d59b019b5c0c15c0108c41699d16b793ebff2c2ecfe6c33fff7176ce2578433292f075d037238bdfaecee7d4cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
